config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :prodottos
  get 'home/index'
  root 'home#index'
  get 'home/regolamento'
  get 'home/descrizione'
  get 'home/contatti'
  get 'home/viso'
  get 'home/corpo'
  get 'home/capelli'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prodotto.rb
class Prodotto < ApplicationRecord
	belongs_to :user
	mount_uploader :image, ImageUploaderUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :prodottos


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def regolamento
  end

  def descrizone
  end

  def contatti
  end

  def viso
  end

  def corpo
  end

  def capelli
  end
end

app/controllers/prodottos_controller.rb
class ProdottosController < ApplicationController
  before_action :set_prodotto, only: [ :show ,:edit, :update, :destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /prodottos or /prodottos.json
  def index
    @prodottos = Prodotto.all
  end

  # GET /prodottos/1 or /prodottos/1.json
  def show
  end

  # GET /prodottos/new
  def new
    #@prodotto = Prodotto.new
    @prodotto = current_user.prodottos.build
  end

  # GET /prodottos/1/edit
  def edit
  end

  # POST /prodottos or /prodottos.json
  def create
    #@prodotto = Prodotto.new(prodotto_params)
    @prodotto = current_user.prodottos.build(prodotto_params)

    respond_to do |format|
      if @prodotto.save
        format.html { redirect_to @prodotto, notice: "Prodotto was successfully created." }
        format.json { render :show, status: :created, location: @prodotto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prodotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prodottos/1 or /prodottos/1.json
  def update
    respond_to do |format|
      if @prodotto.update(prodotto_params)
        format.html { redirect_to @prodotto, notice: "Prodotto was successfully updated." }
        format.json { render :show, status: :ok, location: @prodotto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prodotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prodottos/1 or /prodottos/1.json
  def destroy
    @prodotto.destroy
    respond_to do |format|
      format.html { redirect_to prodottos_url, notice: "Prodotto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @prodotto = current_user.prodottos.find_by(id: params[:id])
    redirect_to prodottos_path, notice:"Not authorized to edit this prodotto" if @prodotto.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prodotto
      @prodotto = Prodotto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prodotto_params
      params.require(:prodotto).permit(:marca, :nome, :categoria, :contenuto, :utilizzo, :media_voti, :user_id, :image, :image_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prodottos_helper.rb
module ProdottosHelper
end

app/views/home/_footer.html.erb
<ul class="nav justify-content-end">
  
  <li class="nav-item">
  	<%= link_to 'Descrizione', home_descrizione_path,class:"nav-link" %>
    
  </li>
  <li class="nav-item">
    <%= link_to 'Contatti', home_contatti_path,class:"nav-link" %>
  </li>
  
</ul>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Skinetics', root_path,class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path,class:"nav-link" %>
        
      </li>
      <li class="nav-item">
        <%= link_to 'Regolamento', home_regolamento_path,class:"nav-link" %>
        
      </li>

       </li>
      
      

      <% if user_signed_in? %>

      <li class="nav-item">
        <%= link_to 'Prodotto', prodottos_path,class:"nav-link" %>
        
         </li>

      <li class="nav-item">
        <%= link_to 'Inserisci prodotto', new_prodotto_path,class:"nav-link" %>
        
      </li>

      <li class="nav-item">
        <%= link_to 'Edit Profile',  edit_user_registration_path,class:"nav-link" %>
        
      </li>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        
      </li>

      <% else %>

      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path,class:"nav-link" %>
        
      </li>
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path,class:"nav-link" %>
        
      
     
      </li>
     <% end %>
     
    </ul>
    
  </div>
</nav>

app/views/home/contatti.html.erb
<script type="text/javascript">
 $(document).ready(function(){
  setTimeout(function(){
    $('#flash').remove();
  }, 4000);
 })
</script>

<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital@1&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@1,900&display=swap" rel="stylesheet">




<div class="center jumbotron contact">
 <div class="row">
   <div class="col-md-10 col-md-offset-1">
       <div class="row">
           <div class="col-md-4 col-md-offset-1"></div>
           <div class="col-md-6"></div>
       </div>
   </div>
 </div>
 <div class="row" style="padding-top:10px;">
     
   <div class="col-md-10 col-md-offset-1">
    <div class="row">
       <div class="col-md-2 col-md-offset-1"></div>
       <div class="col-md-6">
        <div class="row text-center">
          <h3 style="font-family: 'Merriweather', serif;"> <strong> Hai qualche problema o vuoi suggerirci qualcosa? <br /> Puoi inviarci un'email</strong> </h3><br />
        </div>
          

  <form action="/contact" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="form-group">
    <label for="exampleFormControlInput1">Email</label>
    <%if user_signed_in?%>
    <input type="email" class="form-control" id="contact_email" name="contact[email]" value="<%=current_user.email%>" readonly>
    <%else%>
    <input type="email" required="required" class="form-control" id="contact_email" name="contact[email]" placeholder="Inserisci il tuo indirizzo email...">
    <%end%>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Oggetto</label>
     <input type="text" required="required" class="form-control" id="contact_subject" name="contact[subject]" placeholder="Inserisci l'oggetto del tuo messaggio...">
  </div>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">Messaggio</label>
    <textarea class="form-control" required="required" id="contact_message" rows="3" name="contact[message]" placeholder="Inserisci qui il tuo messaggio..."></textarea>
  </div>
  <div class="row text-center">
   <input type="submit" id="invia" class="btn btn-primary" name="commit" data-disable-with="Invia" value="Invia"/>
  </div>

  </div> </div>
       </div>
   </div>
</div>

app/views/home/descrizione.html.erb
<div class="center jumbotron descrizione" style="text-align: center;">
<h1 style="font-family: 'Rowdies', cursive;  letter-spacing: 1px;">  Descrizione</h1>


  <h3 style="font-family: 'Merriweather', serif;"> <strong> Sei un dermatologo o un appasionato di cosmetica? <br /> Allora questa è la web app adatta per te!</strong> </h3><br />
  <h4 style="font-family: 'Merriweather', serif;">Qui troverai i migliori professionisti del mondo che condivideranno le loro opinioni con te. <br /> <br />
  <br>         
 
  Sarà molto semplice e veloce trovare il prodotto per il momento opportuno. <br /> <br /> 
  Per qualsiasi dubbio o in caso di suggerimenti non esitare a conttatarci.  <br /><br />
  <%if user_signed_in?%>
  <%else%>
 Per qualsiasi dubbio<br /> 
  </h4>
  <%= link_to "Conatattici ora!", home_contatti_path ,class: "btn btn-lg btn-secondary"%>
  <br> <br>
  <h4>Sei ancora curioso? Clicca qui sotto per scoprire<br /> 
  </h4>
  <%= link_to "Registrati ora!", new_user_registration_path, class: "btn btn-lg btn-success" %>
  <%end%>
   </div>
  
</div>

app/views/home/index.html.erb
<div class=" center jumbotron entrato" style="text-align: center;">
  
  <%if user_signed_in?%>
  
  <h1>Buongiorno! </h1>
  <br>
  <h3>Quale tipo di trattamento ti interessa?</h3>
  <br>
 
   
  <div class="card">
              <div class="card-header viso"><a href='ricette?category=Colazione'><%= image_tag("viso.jpeg", :title => "viso", :id => "2", :style => "display: block; margin: 0px auto; width: 150px; height: 150px; cursor: pointer;border-radius: 30%;border: 2.5px solid rgb(29, 29, 29);" )%></a></div>

              
                
                 <%= link_to 'Viso', home_viso_path,class:"nav-link" , class:"btn btn-outline-secondary"%>
             
            </div>
  <div class="card">
              <div class="card-header corpo"><%= image_tag("corpo1.jpeg", :title => "pranzo", :id => "1", :style => "display: block; margin: 0px auto; width: 150px; height: 150px; cursor: pointer;border-radius: 30%; border: 2.5px solid rgb(29, 29, 29);") %></a></div>
              
                 <%= link_to 'Corpo', home_corpo_path,class:"nav-link",class:"btn btn-outline-secondary" %>
            </div>
      

     <div class="card">
              <div class="card-header capelli"><%= image_tag("capelli.jpeg", :title => "cena", :id => "2", :style => "display: block; margin: 0px auto; width: 150px; height: 150px; cursor: pointer;border-radius: 30%;border: 2.5px solid rgb(29, 29, 29);" )%></a></div>

               <%= link_to 'Capelli', home_capelli_path,class:"nav-link", class:"btn btn-outline-secondary"%>
        </div>
        
 
           

  <%else%>
  <h1 class="display-4">Benvenuto su Skinetics!</h1>
  <h3>Clicca qui sotto per registrarti<br /> 
  </h3><br>
  <%= link_to "Registrati ora!", new_user_registration_path, class: "btn btn-lg btn-success" %>
  <%end%>
  
</div>

app/views/home/regolamento.html.erb
<div class="center jumbotron regolamento" >
<h1 style="font-family: 'Rowdies', cursive;  letter-spacing: 1px;">  Regolamento</h1>


  
  <h4 style="font-family: 'Merriweather', serif;">
  <ul>
  <li>Un utente può registrarsi alla web app attraverso facebook oppure inserendo le proprie
credenziali richieste direttamente sulla piattaforma. </li> <br />
  
  </li> 
  <li> Un utente può inserire dei prodotti </li><br />
<li> Tutti gli utenti potranno modificare il proprio username,la password corrente, l'immagine che gli rappresenta
e contattare gli amministratori della web app.</li><br />
<li>  Gli amministratori hanno accesso a tutte le funzionalità. Possono eliminare gli utenti, modificare un prodotto, modificare i voti.</li><br />
</ul>

 
  <%if user_signed_in?%>
  <%else%>
  Per qualsiasi dubbio<br /> 
  </h4>
  <%= link_to "Conatattici ora!", home_contatti_path ,class: "btn btn-lg btn-secondary"%>
  

  <br><br>
 <h4> Non sei ancora registrato?<br /> 
  </h4>
  <%= link_to "Registrati ora!", new_user_registration_path, class: "btn btn-lg btn-success" %>
  <%end%>
  
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-primary" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
  

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Skinetics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
    <%if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <br/><br/>
    <%= yield %>
    <br><br><br>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <br><br><br><br>
    <%= render 'home/footer'%>
  </body>
</html>

app/views/prodottos/_form.html.erb
<%= form_with(model: prodotto) do |form| %>
  <% if prodotto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prodotto.errors.count, "error") %> prohibited this prodotto from being saved:</h2>

      <ul>
        <% prodotto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :marca %>
    <%= form.text_field :marca, class:"form-control",placeholder: "Marca" %>
  </div>

  <div class="field form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, class:"form-control", placeholder: "Nome"%>
  </div>

  
 <br>
  <div class="field form-group">
    <%= form.label :categoria %>
    <%= form.select :categoria,['Viso','Corpo','Capelli'] ,class:"form-control", placeholder: "Categoria"%>

  </div>
   
   <br/>

  <div class="field form-group">
    <%= form.label :contenuto %>
   <%= form.text_area :contenuto,cols: 40, rows: 2,class:"form-control", placeholder: "Contenuto" %>
  </div>
    

  <div class="field form-group">
    <%= form.label :utilizzo %>
    <%= form.text_area :utilizzo,cols: 40, rows: 3, class:"form-control",placeholder: "Utilizzo" %>
  </div>

  <div class="field form-group">
    <%= form.label :media_voti %>
    <%= form.number_field :media_voti, class:"form-control", placeholder: "Media Voti" %>
  </div>

  <div class="field form-group">
    
    <%= form.number_field :user_id,id: :prodotto_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="field form-group">
    <%= form.label :add_image %>
    <%= form.file_field :image, class:"form-control" %>
    <%= form.hidden_field :image_cache %>
  </div>


  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/prodottos/edit.html.erb
<h1>Editing Prodotto</h1>

<%= render 'form', prodotto: @prodotto %>

<%= link_to 'Show', @prodotto %> |
<%= link_to 'Back', prodottos_path %>

app/views/prodottos/index.html.erb
<h1>Prodotti</h1>

<table class="table table-striped table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Marca</th>
      <th>Nome</th>
      <th>Categoria</th>
      <th>Contenuto</th>
      <th>Utilizzo</th>
      <th>Media voti</th>
       <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prodottos.each do |prodotto| %>
      <tr>
        <td><%= prodotto.marca %></td>
        <td><%= prodotto.nome %></td>
        <td><%= prodotto.categoria %></td>
        <td><%= prodotto.contenuto %></td>
        <td><%= prodotto.utilizzo %></td>
        <td><%= prodotto.media_voti %></td>
        <td><%= image_tag prodotto.image.url, width: "100px"%></td>
            
       



        <td><%= link_to 'Show', prodotto %></td>
        <td><%= link_to 'Edit', edit_prodotto_path(prodotto) %></td>
        <td><%= link_to 'Destroy', prodotto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prodotto', new_prodotto_path,class:"btn btn-dark" %>

app/views/prodottos/new.html.erb
<h1>Inserisci Prodotto</h1>

<%= render 'form', prodotto: @prodotto %>
<br>
<%= link_to 'Back', prodottos_path,class:"btn btn-dark" %>

app/views/prodottos/show.html.erb
<div class="jumbotron jumbotron-fluid">
  
<div class="media">
  <%= image_tag @prodotto.image.url, width: "400px",class:"align-self-center mr-3" %>
  
  <div class="media-body">
    <h1 class="md-0"> <%= @prodotto.nome %></h1>
    <p>
      <p><strong>Marca:</strong>
      <%= @prodotto.marca %></p>


      <p>
  <strong>Categoria:</strong>
  <%= @prodotto.categoria %>
</p>

<p>
  <strong>Contenuto:</strong>
  <%= @prodotto.contenuto %>
</p>

<p>
  <strong>Utilizzo:</strong>
  <%= @prodotto.utilizzo %>
</p>

<p>
  <strong>Media voti:</strong>
  <%= @prodotto.media_voti %>
</p></p>
  </div>
</div>

<br>
<br>

<%= link_to 'Edit', edit_prodotto_path(@prodotto),class:"btn btn-dark"%> <br> <br>
<%= link_to 'Back', prodottos_path,class:"btn btn-dark" %>